mongodb:
  build: .
  dockerfile: ./Dockerfile.mongodb

dev_db:
  extends:
    service: mongodb
  volumes:
    - ./data/dev_db:/data/db
  command: mongod --dbpath /data/db
  ports:
    - '127.0.0.1:27777:27777'

production_db:
  extends:
    service: mongodb
  volumes:
    - ./data/production:/data/db
  command: mongod --auth --dbpath /data/db
  ports:
    - '127.0.0.1:28888:28888'
